import styles from "./layoutNav.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <main className={styles.main}>
      <div className={styles.infosContainer}>
        <div className={styles.navContainer}>
          <h4>SIGNAL FAIBLE</h4>
          <div className={styles.controller}>
            <div className={styles.imgContainer}>
              <img src="/icons/battery.svg" alt="" />
            </div>
            <p className={styles.volume}>
              <div className={styles.imgContainer}>
                <img src="/icons/song-off.svg" alt="" />
              </div>
            </p>
          </div>
        </div>
      </div>

      {children}
    </main>
  );
}
