export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body>
      <nav>
        <li>nav</li>
      </nav>
      <div className="scientifiques"></div>

      {children}
    </body>
  );
}
