export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <body>
      <div className="nav-container">
        <h4>signal faible</h4>
        <div className="controller">
          <p>Batterie</p>
          <p>volume</p>
        </div>
      </div>
      <div className="traveler">
        <div className="scientifique">
          <div className="img-container">
            <img src="" alt="" />
          </div>
          <div className="traveler-voice">
            <h4>Scientifique</h4>
            <p>Lottie</p>
          </div>
        </div>
        <h2>Lottie</h2>
      </div>

      {children}
    </body>
  );
}
